// File: photonicsPerfEnergyTables.cpp
// PHOTONICSeval Simulator - Performance and Energy Tables
// Copyright (c) 2024 University of Virginia
// This file is licensed under the MIT License.
// See the LICENSE file in the root of this repository for more details.

#include "photonicsPerfEnergyTables.h"
#include "photonicsCmd.h"
#include <unordered_map>
#include <tuple>


//! @brief  BitSIMD performance table (Tuple: #R, #W, #L)
const std::unordered_map<PhotonicsDeviceEnum, std::unordered_map<PhotonicsDataType,
    std::unordered_map<PhotonicsCmdEnum, std::tuple<unsigned, unsigned, unsigned>>>>
photonicsPerfEnergyTables::bitsimdPerfTable = {
  { PHOTONICS_DEVICE_BITSIMD_V, {
    { PHOTONICS_BOOL, {
      { PhotonicsCmdEnum::NOT,          {    1,    1,    1 } },
      { PhotonicsCmdEnum::AND,          {    2,    1,    2 } },
      { PhotonicsCmdEnum::OR,           {    2,    1,    2 } },
      { PhotonicsCmdEnum::XOR,          {    2,    1,    2 } },
      { PhotonicsCmdEnum::XNOR,         {    2,    1,    2 } },
    }},
    { PHOTONICS_INT8, {
      { PhotonicsCmdEnum::ABS,          {    9,    8,   34 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::SUB,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::MUL,          {   72,   36,  136 } },
      { PhotonicsCmdEnum::DIV,          {  196,  137,  336 } },
      { PhotonicsCmdEnum::NOT,          {    8,    8,    8 } },
      { PhotonicsCmdEnum::AND,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::OR,           {   16,    8,   16 } },
      { PhotonicsCmdEnum::XOR,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::XNOR,         {   16,    8,   24 } },
      { PhotonicsCmdEnum::GT,           {   16,    1,   25 } },
      { PhotonicsCmdEnum::LT,           {   16,    1,   25 } },
      { PhotonicsCmdEnum::EQ,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::NE,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::MIN,          {   32,    8,   41 } },
      { PhotonicsCmdEnum::MAX,          {   32,    8,   41 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {   36,   36,  172 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  146,  145,  394 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {    8,    8,   24 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {    8,    8,   32 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {    8,    1,   33 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {    8,    1,   33 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   16,    8,   57 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   16,    8,   57 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {   44,   44,  197 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   32,    8,   41 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   32,    8,   41 } },
      { PhotonicsCmdEnum::REDMAX,       {   32,    8,   41 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   32,    8,   41 } },
    }},
    { PHOTONICS_INT16, {
      { PhotonicsCmdEnum::ABS,          {   17,   16,   66 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::SUB,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::MUL,          {  272,  136,  528 } },
      { PhotonicsCmdEnum::DIV,          {  772,  469, 1176 } },
      { PhotonicsCmdEnum::NOT,          {   16,   16,   16 } },
      { PhotonicsCmdEnum::AND,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::OR,           {   32,   16,   32 } },
      { PhotonicsCmdEnum::XOR,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::XNOR,         {   32,   16,   48 } },
      { PhotonicsCmdEnum::GT,           {   32,    1,   49 } },
      { PhotonicsCmdEnum::LT,           {   32,    1,   49 } },
      { PhotonicsCmdEnum::EQ,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::NE,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::MIN,          {   64,   16,   81 } },
      { PhotonicsCmdEnum::MAX,          {   64,   16,   81 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  136,  136,  664 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  546,  485, 1418 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   16,   16,   48 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   16,   16,   64 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   16,    1,   65 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   16,    1,   65 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   32,   16,  113 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   32,   16,  113 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  168,  152,  713 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   64,   16,   81 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   64,   16,   81 } },
      { PhotonicsCmdEnum::REDMAX,       {   64,   16,   81 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   64,   16,   81 } },
    }},
    { PHOTONICS_INT32, {
      { PhotonicsCmdEnum::ABS,          {   33,   32,  130 } },
      { PhotonicsCmdEnum::POPCOUNT,     {  114,  114,  218 } },
      { PhotonicsCmdEnum::ADD,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::SUB,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::MUL,          { 1056,  528, 2080 } },
      { PhotonicsCmdEnum::DIV,          { 3076, 1709, 4392 } },
      { PhotonicsCmdEnum::NOT,          {   32,   32,   32 } },
      { PhotonicsCmdEnum::AND,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::OR,           {   64,   32,   64 } },
      { PhotonicsCmdEnum::XOR,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::XNOR,         {   64,   32,   96 } },
      { PhotonicsCmdEnum::GT,           {   64,    1,   97 } },
      { PhotonicsCmdEnum::LT,           {   64,    1,   97 } },
      { PhotonicsCmdEnum::EQ,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::NE,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::MIN,          {  128,   32,  161 } },
      { PhotonicsCmdEnum::MAX,          {  128,   32,  161 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  528,  528, 2608 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   { 2114, 1741, 5386 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   32,   32,   96 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   32,   32,  128 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   32,    1,  129 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   32,    1,  129 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   64,   32,  225 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   64,   32,  225 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  128,   32,  161 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  128,   32,  161 } },
      { PhotonicsCmdEnum::REDMAX,       {  128,   32,  161 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  128,   32,  161 } },
    }},
    { PHOTONICS_INT64, {
      { PhotonicsCmdEnum::ABS,          {   65,   64,  258 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::SUB,          {  128,   64,  193 } },
      //{ PhotonicsCmdEnum::MUL,          {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV,          {    0,    0,    0 } },
      { PhotonicsCmdEnum::NOT,          {   64,   64,   64 } },
      { PhotonicsCmdEnum::AND,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::OR,           {  128,   64,  128 } },
      { PhotonicsCmdEnum::XOR,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::XNOR,         {  128,   64,  192 } },
      { PhotonicsCmdEnum::GT,           {  128,    1,  193 } },
      { PhotonicsCmdEnum::LT,           {  128,    1,  193 } },
      { PhotonicsCmdEnum::EQ,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::NE,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::MIN,          {  256,   64,  321 } },
      { PhotonicsCmdEnum::MAX,          {  256,   64,  321 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   64,   64,  257 } },
      //{ PhotonicsCmdEnum::MUL_SCALAR,   {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV_SCALAR,   {    0,    0,    0 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   64,   64,  192 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   64,   64,  256 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   64,    1,  257 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   64,    1,  257 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {  128,   64,  449 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {  128,   64,  449 } },
      //{ PhotonicsCmdEnum::SCALED_ADD,   {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  256,   64,  321 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  256,   64,  321 } },
      { PhotonicsCmdEnum::REDMAX,       {  256,   64,  321 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  256,   64,  321 } },
    }},
    { PHOTONICS_UINT8, {
      { PhotonicsCmdEnum::ABS,          {    8,    8,    0 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::SUB,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::MUL,          {   72,   36,  136 } },
      { PhotonicsCmdEnum::DIV,          {  216,  140,  297 } },
      { PhotonicsCmdEnum::NOT,          {    8,    8,    8 } },
      { PhotonicsCmdEnum::AND,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::OR,           {   16,    8,   16 } },
      { PhotonicsCmdEnum::XOR,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::XNOR,         {   16,    8,   24 } },
      { PhotonicsCmdEnum::GT,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::LT,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::EQ,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::NE,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::MIN,          {   32,    8,   42 } },
      { PhotonicsCmdEnum::MAX,          {   32,    8,   42 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {   36,   36,  172 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  152,  140,  361 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {    8,    8,   24 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {    8,    8,   32 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   16,    8,   58 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   16,    8,   58 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {   44,   44,  197 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   32,    8,   42 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   32,    8,   42 } },
      { PhotonicsCmdEnum::REDMAX,       {   32,    8,   42 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   32,    8,   42 } },
      { PhotonicsCmdEnum::AES_SBOX,     {   2450, 2112, 3625 } },
      { PhotonicsCmdEnum::AES_INVERSE_SBOX,     {   2420, 2086, 3610 } },
    }},
    { PHOTONICS_UINT16, {
      { PhotonicsCmdEnum::ABS,          {   16,   16,    0 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::SUB,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::MUL,          {  272,  136,  528 } },
      { PhotonicsCmdEnum::DIV,          {  816,  472, 1105 } },
      { PhotonicsCmdEnum::NOT,          {   16,   16,   16 } },
      { PhotonicsCmdEnum::AND,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::OR,           {   32,   16,   32 } },
      { PhotonicsCmdEnum::XOR,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::XNOR,         {   32,   16,   48 } },
      { PhotonicsCmdEnum::GT,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::LT,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::EQ,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::NE,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::MIN,          {   64,   16,   82 } },
      { PhotonicsCmdEnum::MAX,          {   64,   16,   82 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  136,  136,  664 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  560,  472, 1361 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   16,   16,   48 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   16,   16,   64 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   32,   16,  114 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   32,   16,  114 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  168,  152,  713 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   64,   16,   82 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   64,   16,   82 } },
      { PhotonicsCmdEnum::REDMAX,       {   64,   16,   82 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   64,   16,   82 } },
    }},
    { PHOTONICS_UINT32, {
      { PhotonicsCmdEnum::ABS,          {   32,   32,    0 } },
      { PhotonicsCmdEnum::POPCOUNT,     {  114,  114,  218 } },
      { PhotonicsCmdEnum::ADD,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::SUB,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::MUL,          { 1056,  528, 2080 } },
      { PhotonicsCmdEnum::DIV,          { 3168, 1712, 4257 } },
      { PhotonicsCmdEnum::NOT,          {   32,   32,   32 } },
      { PhotonicsCmdEnum::AND,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::OR,           {   64,   32,   64 } },
      { PhotonicsCmdEnum::XOR,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::XNOR,         {   64,   32,   96 } },
      { PhotonicsCmdEnum::GT,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::LT,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::EQ,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::NE,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::MIN,          {  128,   32,  162 } },
      { PhotonicsCmdEnum::MAX,          {  128,   32,  162 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  528,  528, 2608 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   { 2144, 1712, 5281 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   32,   32,   96 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   32,   32,  128 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   64,   32,  226 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   64,   32,  226 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  128,   32,  162 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  128,   32,  162 } },
      { PhotonicsCmdEnum::REDMAX,       {  128,   32,  162 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  128,   32,  162 } },
    }},
    { PHOTONICS_UINT64, {
      { PhotonicsCmdEnum::ABS,          {   64,   64,    0 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::SUB,          {  128,   64,  193 } },
      //{ PhotonicsCmdEnum::MUL,          {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV,          {    0,    0,    0 } },
      { PhotonicsCmdEnum::NOT,          {   64,   64,   64 } },
      { PhotonicsCmdEnum::AND,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::OR,           {  128,   64,  128 } },
      { PhotonicsCmdEnum::XOR,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::XNOR,         {  128,   64,  192 } },
      { PhotonicsCmdEnum::GT,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::LT,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::EQ,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::NE,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::MIN,          {  256,   64,  322 } },
      { PhotonicsCmdEnum::MAX,          {  256,   64,  322 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   64,   64,  257 } },
      //{ PhotonicsCmdEnum::MUL_SCALAR,   {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV_SCALAR,   {    0,    0,    0 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   64,   64,  192 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   64,   64,  256 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {  128,   64,  450 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {  128,   64,  450 } },
      // { PhotonicsCmdEnum::SCALED_ADD,  {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  256,   64,  322 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  256,   64,  322 } },
      { PhotonicsCmdEnum::REDMAX,       {  256,   64,  322 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  256,   64,  322 } },
    }},
    { PHOTONICS_FP32, {
      { PhotonicsCmdEnum::ADD,          { 1331,  685, 1687 } },
      { PhotonicsCmdEnum::SUB,          { 1331,  685, 1687 } },
      { PhotonicsCmdEnum::MUL,          { 1852, 1000, 3054 } },
      { PhotonicsCmdEnum::DIV,          { 2744, 1458, 4187 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   { 1852, 1000, 3054 } },
    }}
  }},
  { PHOTONICS_DEVICE_BITSIMD_V_AP, {
    { PHOTONICS_BOOL, {
      { PhotonicsCmdEnum::NOT,          {    1,    1,    1 } },
      { PhotonicsCmdEnum::AND,          {    2,    1,    2 } },
      { PhotonicsCmdEnum::OR,           {    2,    1,    2 } },
      { PhotonicsCmdEnum::XOR,          {    2,    1,    2 } },
      { PhotonicsCmdEnum::XNOR,         {    2,    1,    2 } },
    }},
    { PHOTONICS_INT8, {
      { PhotonicsCmdEnum::ABS,          {    9,    8,   51 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::SUB,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::MUL,          {   72,   36,  136 } },
      { PhotonicsCmdEnum::DIV,          {  196,  137,  493 } },
      { PhotonicsCmdEnum::NOT,          {    8,    8,    8 } },
      { PhotonicsCmdEnum::AND,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::OR,           {   16,    8,   17 } },
      { PhotonicsCmdEnum::XOR,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::XNOR,         {   16,    8,   16 } },
      { PhotonicsCmdEnum::GT,           {   16,    1,   33 } },
      { PhotonicsCmdEnum::LT,           {   16,    1,   33 } },
      { PhotonicsCmdEnum::EQ,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::NE,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::MIN,          {   32,    8,   49 } },
      { PhotonicsCmdEnum::MAX,          {   32,    8,   49 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {   36,   36,  172 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  146,  145,  551 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {    8,    8,   25 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {    8,    8,   24 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {    8,    1,   41 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {    8,    1,   41 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   16,    8,   65 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   16,    8,   65 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {   52,   44,  197 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   32,    8,   49 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   32,    8,   49 } },
      { PhotonicsCmdEnum::REDMAX,       {   32,    8,   49 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   32,    8,   49 } },
    }},
    { PHOTONICS_INT16, {
      { PhotonicsCmdEnum::ABS,          {   17,   16,   99 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::SUB,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::MUL,          {  272,  136,  528 } },
      { PhotonicsCmdEnum::DIV,          {  772,  469, 1741 } },
      { PhotonicsCmdEnum::NOT,          {   16,   16,   16 } },
      { PhotonicsCmdEnum::AND,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::OR,           {   32,   16,   33 } },
      { PhotonicsCmdEnum::XOR,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::XNOR,         {   32,   16,   32 } },
      { PhotonicsCmdEnum::GT,           {   32,    1,   65 } },
      { PhotonicsCmdEnum::LT,           {   32,    1,   65 } },
      { PhotonicsCmdEnum::EQ,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::NE,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::MIN,          {   64,   16,   97 } },
      { PhotonicsCmdEnum::MAX,          {   64,   16,   97 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  136,  136,  664 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  546,  485, 1983 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   16,   16,   49 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   16,   16,   48 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   16,    1,   81 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   16,    1,   81 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   32,   16,  129 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   32,   16,  129 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  168,  152,  713 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   64,   16,   97 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   64,   16,   97 } },
      { PhotonicsCmdEnum::REDMAX,       {   64,   16,   97 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   64,   16,   97 } },
    }},
    { PHOTONICS_INT32, {
      { PhotonicsCmdEnum::ABS,          {   33,   32,  195 } },
      { PhotonicsCmdEnum::POPCOUNT,     {  114,  114,  317 } },
      { PhotonicsCmdEnum::ADD,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::SUB,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::MUL,          { 1056,  528, 2080 } },
      { PhotonicsCmdEnum::DIV,          { 3076, 1709, 6541 } },
      { PhotonicsCmdEnum::NOT,          {   32,   32,   32 } },
      { PhotonicsCmdEnum::AND,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::OR,           {   64,   32,   65 } },
      { PhotonicsCmdEnum::XOR,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::XNOR,         {   64,   32,   64 } },
      { PhotonicsCmdEnum::GT,           {   64,    1,  129 } },
      { PhotonicsCmdEnum::LT,           {   64,    1,  129 } },
      { PhotonicsCmdEnum::EQ,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::NE,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::MIN,          {  128,   32,  193 } },
      { PhotonicsCmdEnum::MAX,          {  128,   32,  193 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  528,  528, 2608 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   { 2114, 1741, 7535 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   32,   32,   97 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   32,   32,   96 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   32,    1,  161 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   32,    1,  161 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   64,   32,  257 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   64,   32,  257 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  128,   32,  193 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  128,   32,  193 } },
      { PhotonicsCmdEnum::REDMAX,       {  128,   32,  193 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  128,   32,  193 } },
    }},
    { PHOTONICS_INT64, {
      { PhotonicsCmdEnum::ABS,          {   65,   64,  387 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::SUB,          {  128,   64,  193 } },
      //{ PhotonicsCmdEnum::MUL,          {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV,          {    0,    0,    0 } },
      { PhotonicsCmdEnum::NOT,          {   64,   64,   64 } },
      { PhotonicsCmdEnum::AND,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::OR,           {  128,   64,  129 } },
      { PhotonicsCmdEnum::XOR,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::XNOR,         {  128,   64,  128 } },
      { PhotonicsCmdEnum::GT,           {  128,    1,  257 } },
      { PhotonicsCmdEnum::LT,           {  128,    1,  257 } },
      { PhotonicsCmdEnum::EQ,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::NE,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::MIN,          {  256,   64,  385 } },
      { PhotonicsCmdEnum::MAX,          {  256,   64,  385 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   64,   64,  257 } },
      //{ PhotonicsCmdEnum::MUL_SCALAR,   {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV_SCALAR,   {    0,    0,    0 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   64,   64,  193 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   64,   64,  192 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   64,    1,  321 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   64,    1,  321 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {  128,   64,  513 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {  128,   64,  513 } },
      // { PhotonicsCmdEnum::SCALED_ADD,  {   52,   44,  197 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  256,   64,  385 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  256,   64,  385 } },
      { PhotonicsCmdEnum::REDMAX,       {  256,   64,  385 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  256,   64,  385 } },
    }},
    { PHOTONICS_UINT8, {
      { PhotonicsCmdEnum::ABS,          {    8,    8,    0 } },
      { PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::SUB,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::MUL,          {   72,   36,  136 } },
      { PhotonicsCmdEnum::DIV,          {  216,  140,  433 } },
      { PhotonicsCmdEnum::NOT,          {    8,    8,    8 } },
      { PhotonicsCmdEnum::AND,          {   16,    8,   16 } },
      { PhotonicsCmdEnum::OR,           {   16,    8,   17 } },
      { PhotonicsCmdEnum::XOR,          {   16,    8,   25 } },
      { PhotonicsCmdEnum::XNOR,         {   16,    8,   16 } },
      { PhotonicsCmdEnum::GT,           {   16,    1,   35 } },
      { PhotonicsCmdEnum::LT,           {   16,    1,   35 } },
      { PhotonicsCmdEnum::EQ,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::NE,           {   16,    1,   26 } },
      { PhotonicsCmdEnum::MIN,          {   32,    8,   51 } },
      { PhotonicsCmdEnum::MAX,          {   32,    8,   51 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {   36,   36,  172 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  152,  140,  497 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {    8,    8,   24 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {    8,    8,   25 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {    8,    8,   33 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {    8,    8,   24 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {    8,    1,   43 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {    8,    1,   43 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {    8,    1,   34 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   16,    8,   67 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   16,    8,   67 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {   52,   44,  197 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   32,    8,   51 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   32,    8,   51 } },
      { PhotonicsCmdEnum::REDMAX,       {   32,    8,   51 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   32,    8,   51 } },
      { PhotonicsCmdEnum::AES_SBOX,     {   2450, 2112, 3625 } },
      { PhotonicsCmdEnum::AES_INVERSE_SBOX,     {   2420, 2086, 3610 } },
    }},
    { PHOTONICS_UINT16, {
      { PhotonicsCmdEnum::ABS,          {   16,   16,    0 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::SUB,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::MUL,          {  272,  136,  528 } },
      { PhotonicsCmdEnum::DIV,          {  816,  472, 1633 } },
      { PhotonicsCmdEnum::NOT,          {   16,   16,   16 } },
      { PhotonicsCmdEnum::AND,          {   32,   16,   32 } },
      { PhotonicsCmdEnum::OR,           {   32,   16,   33 } },
      { PhotonicsCmdEnum::XOR,          {   32,   16,   49 } },
      { PhotonicsCmdEnum::XNOR,         {   32,   16,   32 } },
      { PhotonicsCmdEnum::GT,           {   32,    1,   67 } },
      { PhotonicsCmdEnum::LT,           {   32,    1,   67 } },
      { PhotonicsCmdEnum::EQ,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::NE,           {   32,    1,   50 } },
      { PhotonicsCmdEnum::MIN,          {   64,   16,   99 } },
      { PhotonicsCmdEnum::MAX,          {   64,   16,   99 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  136,  136,  664 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   {  560,  472, 1889 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   16,   16,   48 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   16,   16,   49 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   16,   16,   65 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   16,   16,   48 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   16,    1,   83 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   16,    1,   83 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   16,    1,   66 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   32,   16,  131 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   32,   16,  131 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  168,  152,  713 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {   64,   16,   99 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {   64,   16,   99 } },
      { PhotonicsCmdEnum::REDMAX,       {   64,   16,   99 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {   64,   16,   99 } },
    }},
    { PHOTONICS_UINT32, {
      { PhotonicsCmdEnum::ABS,          {   32,   32,    0 } },
      { PhotonicsCmdEnum::POPCOUNT,     {  114,  114,  317 } },
      { PhotonicsCmdEnum::ADD,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::SUB,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::MUL,          { 1056,  528, 2080 } },
      { PhotonicsCmdEnum::DIV,          { 3168, 1712, 6337 } },
      { PhotonicsCmdEnum::NOT,          {   32,   32,   32 } },
      { PhotonicsCmdEnum::AND,          {   64,   32,   64 } },
      { PhotonicsCmdEnum::OR,           {   64,   32,   65 } },
      { PhotonicsCmdEnum::XOR,          {   64,   32,   97 } },
      { PhotonicsCmdEnum::XNOR,         {   64,   32,   64 } },
      { PhotonicsCmdEnum::GT,           {   64,    1,  131 } },
      { PhotonicsCmdEnum::LT,           {   64,    1,  131 } },
      { PhotonicsCmdEnum::EQ,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::NE,           {   64,    1,   98 } },
      { PhotonicsCmdEnum::MIN,          {  128,   32,  195 } },
      { PhotonicsCmdEnum::MAX,          {  128,   32,  195 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   {  528,  528, 2608 } },
      { PhotonicsCmdEnum::DIV_SCALAR,   { 2144, 1712, 7361 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   32,   32,   96 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   32,   32,   97 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   32,   32,  129 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   32,   32,   96 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   32,    1,  163 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   32,    1,  163 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   32,    1,  130 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {   64,   32,  259 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {   64,   32,  259 } },
      { PhotonicsCmdEnum::SCALED_ADD,   {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  128,   32,  195 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  128,   32,  195 } },
      { PhotonicsCmdEnum::REDMAX,       {  128,   32,  195 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  128,   32,  195 } },
    }},
    { PHOTONICS_UINT64, {
      { PhotonicsCmdEnum::ABS,          {   64,   64,    0 } },
      //{ PhotonicsCmdEnum::POPCOUNT,     {    0,    0,    0 } },
      { PhotonicsCmdEnum::ADD,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::SUB,          {  128,   64,  193 } },
      //{ PhotonicsCmdEnum::MUL,          {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV,          {    0,    0,    0 } },
      { PhotonicsCmdEnum::NOT,          {   64,   64,   64 } },
      { PhotonicsCmdEnum::AND,          {  128,   64,  128 } },
      { PhotonicsCmdEnum::OR,           {  128,   64,  129 } },
      { PhotonicsCmdEnum::XOR,          {  128,   64,  193 } },
      { PhotonicsCmdEnum::XNOR,         {  128,   64,  128 } },
      { PhotonicsCmdEnum::GT,           {  128,    1,  259 } },
      { PhotonicsCmdEnum::LT,           {  128,    1,  259 } },
      { PhotonicsCmdEnum::EQ,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::NE,           {  128,    1,  194 } },
      { PhotonicsCmdEnum::MIN,          {  256,   64,  387 } },
      { PhotonicsCmdEnum::MAX,          {  256,   64,  387 } },
      { PhotonicsCmdEnum::ADD_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::SUB_SCALAR,   {   64,   64,  257 } },
      //{ PhotonicsCmdEnum::MUL_SCALAR,   {    0,    0,    0 } },
      //{ PhotonicsCmdEnum::DIV_SCALAR,   {    0,    0,    0 } },
      { PhotonicsCmdEnum::AND_SCALAR,   {   64,   64,  192 } },
      { PhotonicsCmdEnum::OR_SCALAR,    {   64,   64,  193 } },
      { PhotonicsCmdEnum::XOR_SCALAR,   {   64,   64,  257 } },
      { PhotonicsCmdEnum::XNOR_SCALAR,  {   64,   64,  192 } },
      { PhotonicsCmdEnum::GT_SCALAR,    {   64,    1,  323 } },
      { PhotonicsCmdEnum::LT_SCALAR,    {   64,    1,  323 } },
      { PhotonicsCmdEnum::EQ_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::NE_SCALAR,    {   64,    1,  258 } },
      { PhotonicsCmdEnum::MIN_SCALAR,   {  128,   64,  515 } },
      { PhotonicsCmdEnum::MAX_SCALAR,   {  128,   64,  515 } },
      // { PhotonicsCmdEnum::SCALED_ADD,  {  592,  560, 2705 } }, // Derived from adding ADD + MUL_SCALAR
      { PhotonicsCmdEnum::REDMIN,       {  256,   64,  387 } },
      { PhotonicsCmdEnum::REDMIN_RANGE, {  256,   64,  387 } },
      { PhotonicsCmdEnum::REDMAX,       {  256,   64,  387 } },
      { PhotonicsCmdEnum::REDMAX_RANGE, {  256,   64,  387 } },
    }},
    { PHOTONICS_FP32, {
      { PhotonicsCmdEnum::ADD,          { 1597,  822, 2024 } },
      { PhotonicsCmdEnum::SUB,          { 1597,  822, 2024 } },
      { PhotonicsCmdEnum::MUL,          { 2222, 1200, 3664 } },
      { PhotonicsCmdEnum::DIV,          { 3292, 1749, 5024 } },
      { PhotonicsCmdEnum::MUL_SCALAR,   { 2222, 1200, 3664 } },
    }}
  }},
};


